build_from:
  aarch64: ghcr.io/hassio-addons/base:12.0.0
  amd64: ghcr.io/hassio-addons/base:12.0.0
  armhf: ghcr.io/hassio-addons/base:12.0.0
  armv7: ghcr.io/hassio-addons/base:12.0.0
  i386: ghcr.io/hassio-addons/base:12.0.0

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Telegram Replicator"
  org.opencontainers.image.description: "Telegram üzenetek automatikus másolása egyik csatornából a másikba"
  org.opencontainers.image.licenses: "MIT"

args:
  BUILD_DESCRIPTION: "Telegram üzenetek automatikus másolása egyik csatornából a másikba"
  BUILD_NAME: "Telegram Replicator" 